METHOD:
  BBQ:
    SCORE_FN: AIC
  GROUPING: per-class
  MAINTAIN_RANK: true
  NAME: BBQ
  PER_CLASS:
    MISSING_SCORE: zero
    NO_TP_SCORE: zero
NAME: Calibrate with AIC
TEST:
  MAX_DETS_EVAL: -1
TRAIN:
  TRAIN_SET: custom
VISUALIZE: true
_BASE_: ./base.yaml
