METHOD:
  GROUPING: per-class
  MAINTAIN_RANK: true
  NAME: TemperatureScaling
  PER_CLASS:
    MISSING_SCORE: zero
    NO_TP_SCORE: zero
NAME: Calibrate with Temperature Scaling
TEST:
  MAX_DETS_EVAL: -1
TRAIN:
  TRAIN_SET: custom
VISUALIZE: true
_BASE_: ./base.yaml
